# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 982ef207cd4709f7b863f7a24dd4584a7086f87e95115f4bc3aa45ef6afd9d47427b85ef78fd0765354372a483f2158b4544726be2a1166be6ee6fa695a03f67

test:
  secret_key_base: 37b9ad0d0b08b621fd14467e58c16ed84a8c2603f131b8ccb06b4301ccc578485d6adffb1817f7c750f5cd762ea6e5adf2962c076872df3aa7473064794b3509

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
